server:
  port: 9005
  servlet:
    context-path: /iot

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: iot-data-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bit_iot?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: chenhao1998@

tdengine:
  jdbc-url: jdbc:TAOS-RS://localhost:6041/bit_iot_ts
  username: root
  password: taosdata
  super-table: device_data
  connect-timeout-seconds: 5
  query-timeout-seconds: 30
  max-limit-per-query: 5000

knife4j:
  enable: true
  setting:
    language: zh_cn
